### ISSUE TITLE
example simulated IR.py

### ISSUE THREAD

**Issue by david1412** [david1412/Time-varying--MIMO#4]
The h values are zero in the simulated_iR.py .. where the SISO.py has h = impulse responses array values .. 

1. i cannot compare the impulse responses .

https://github.com/david1412/Time-varying--MIMO/blob/8a2d27ce9b7567ad1e803a41dc4292f7efc7be31/example_simulate_IRs.py#L29

**Comment by narahahn** [comment]
Are you sure? I got these impulse responses!

![irs](https://user-images.githubusercontent.com/8125968/33275805-fb3052c2-d393-11e7-9069-c4dd1fc613eb.png)

**Comment by david1412** [comment]
I got the same plot 

but in kernel : 

h
Out[4]: 
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

**Comment by narahahn** [comment]
It only shows that the first and last three elements of each column are zeros. There are nonzero elements somewhere in the middle.

This is also shown In the 2D plot above. Most of the elements in each column are zeros and only a few elements are nonzero (red).

**Comment by david1412** [comment]
i used this format to compare the impulse responses ..
plt.figure(figsize=(10,4))
plt.subplot(121)
plt.imshow(impulse_response) # I got the plot

plt.subplot(122)
plt.imshow(np.rad2deg(phi_target),time.h.T) # in your code , you used pcolormesh , cmap, and  h.T( what is T in simulated IR.py) as i observed 
time  = np.arange(0, N) / fs * 1000 ( simulated IR.py code) 
time = time = np.arange(np.ceil(L)) / fs ( SISO.py code) 

I am little bit confused with the time ? and comparison. 
System identification is in process , i will send by evening .

**Comment by david1412** [comment]
system distance about to complete the task ,( system identification)*

**Comment by narahahn** [comment]
If you make changes to a file, please push the change to the repository rather than create a new file and add it. This would make it more easy to track the changes you made.

**2D Plot**
The difference between `imshow` and `pcolormesh` is briefly explained [here](http://thomas-cokelaer.info/blog/2014/05/matplotlib-difference-between-pcolor-pcolormesh-and-imshow/). For more details, check the Matplotlib docuements: [`imshow`](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.imshow.html) and [`pcolormesh`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.pcolormesh.html).

**Transpose**
`h.T` is the transpose of the array `h`, so the column and row indices are switched. I did this in order to have the angle in the horizontal axis and the time in the vertical axis in my plot.

**Time axes**
The former is the time in ms (millisecond) while the latter in s (second). See the axis label in the above plot.
